version: '3.9'
services:
  
  clubseek:
    build: .
    ports:
    - "8000:3000"
    depends_on:
      clubdatabases:
        condition: service_healthy
    secrets:
      - application_credentials
      - db_uri
    links:
    - clubdatabases

  clubdatabases:
    image: mysql:8.0.28-oracle
    environment:
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: clubdatabase
    secrets:
      - db_user
      - db_password
      - db_root_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      retries: 10
    volumes:
      - ./databaseInit:/docker-entrypoint-initdb.d

secrets:
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password
  db_root_password:
    file: ./secrets/db_root_password
  db_uri:
    file: ./secrets/db_uri
  application_credentials:
    file: ./secrets/application_credentials