version: '3.9'
services:
  
  integrationtest:
    build: .
    command: "poetry run pytest tests/test_integration_clubseek.py -v --durations=0"
    depends_on:
      clubseek:
        condition: service_started
    secrets:
      - db_uri
      - application_credentials
    links:
    - clubseek

secrets:
  application_credentials:
    file: ./secrets/application_credentials
  db_uri:
    file: ./secrets/db_uri