version: '3.9'
services:
  
  clubseek:
    build: .
    command: "poetry run pytest tests/test_unit_clubseek.py"
    secrets:
      - db_uri
      - application_credentials

secrets:
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password
  application_credentials:
    file: ./secrets/application_credentials
  db_uri:
    file: ./secrets/db_uri